--- #YAML:1.0
name: Algorithm-NaiveBayes
version: 0.03
author:
  - Ken Williams, ken@mathforum.org
abstract: Bayesian prediction of categories
license: perl
requires:
  List::Util: 0
provides:
  Algorithm::NaiveBayes:
    file: lib/Algorithm/NaiveBayes.pm
    version: 0.03
  Algorithm::NaiveBayes::Model::Discrete:
    file: lib/Algorithm/NaiveBayes/Model/Discrete.pm
  Algorithm::NaiveBayes::Model::Frequency:
    file: lib/Algorithm/NaiveBayes/Model/Frequency.pm
  Algorithm::NaiveBayes::Model::Gaussian:
    file: lib/Algorithm/NaiveBayes/Model/Gaussian.pm
  Algorithm::NaiveBayes::Util:
    file: lib/Algorithm/NaiveBayes/Util.pm
generated_by: Module::Build version 0.25
